import type { Metadata } from "next";
import "./globals.css";
import ExpenseProvider from "./expenseProvider";
import { ThemeProvider } from "next-themes";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className={"md:flex md:items-center md:flex-col sm:flex-none"}>
        <ThemeProvider attribute="class">
          <ExpenseProvider>{children}</ExpenseProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
