import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ExpenseProvider from "./expenseProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={"md:flex md:items-center md:flex-col sm:flex-none"}>
        <ExpenseProvider>{children}</ExpenseProvider>
      </body>
    </html>
  );
}
